fix: fix es6 output *.js for imports for esm compat
syavorsky/comment-parser pull request #161
Opened 2022-11-06 03:35 UTC by mostlylikeable

There's another pr (https://github.com/syavorsky/comment-parser/pull/160) to manually update `.d.ts` files with the correct extension. Not sure if this is wanted or not, but it _should_ remove the need to manually update the imports in esm files.

es6 output files did not have native esm compatible imports. The imports were missing `.js` extension at the end. This caused problems trying to use them when using `--moduleResolution node16`.

_NOTE: the missing `.js` extension would not affect projects that set `"skipLibCheck": true`._

#### changes
- set `tsconfig.json` `"module": "node16"`
- set `tsconfig.json` `"moduleResolution": "node16"`
- add `$schema` to tsconfigs to remove ide warning about `node16` not being valid
- update imports to end with `*.js`
- configure jest for esm (non-test files only)
- removed a few unused imports
- removed manual import update step in `build` script

#### lib updates
- upgrade typescript `^4.3.4` to `^4.8.3`
- upgrade jest `^27.0.5` to `^29.2.0`
  - this pulls in updated sourcemaps that doesn't have wasm issue with node 18
- upgrade ts-jest `^27.0.3` to `^29.0.3`

Closes: https://github.com/syavorsky/comment-parser/issues/159

2023-01-20 16:42 UTC, ChristianMurphy requested changes
Thanks @mostlylikeable!
I ran into the same issue recently.
This looks like it mostly resolves the issue, a few ideas on how to get it across the finish line:

In _package.json_ `exports` need to be given a `types` attribute to resolve the typings for explicitly listed files.
See: https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing for more information

2023-01-20 16:42 UTC, ChristianMurphy commented on tsconfig.json
> +    "moduleResolution": "node16",
When `"module": "node16"`, the `"moduleResolution"` is automatically set, this isn't needed

```suggestion
```

2023-07-31 08:17 UTC, brettz9 commented
I think this PR can be dropped now that #163 was merged.

2023-08-01 06:31 UTC, syavorsky commented
closing in favor to #163. The`comment-parser@1.4.0` version with the fix is out

2023-08-01 06:31 UTC, closed without merging